// <auto-generated />
namespace VetPet.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreatePetsCatalog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatePetsCatalog));
        
        string IMigrationMetadata.Id
        {
            get { return "201704012218016_CreatePetsCatalog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
